### ISSUE TITLE
Install.sh placing cfg files in old configuration folder.

### ISSUE THREAD

**Issue by LAP87** [moggieuk/ERCF-Software-V3#16]
Hi, since the latest moonraker/klipper setup now has the config files in /home/pi/printer_data/config, everything has to be moved and renamed manually before it starts working after running your install.sh.
The py file gets linked properly to the klippy folder still.
Just a heads up,

Ps.
Also i can't seem to get a usable calibration out of your script, where the toolhead sensorless ercf software rams filament violently into the extruder, yours doesn't even reach the extruder before giving up.. (every parameter copied from otherwise tuned ercf) 
I'm about to give up xD

**Comment by moggieuk** [comment]
Sorry for the late response, but two things:

In the README it explains that you can override the location of install using "-c" and "-k" flags.   However that is not necessary now because both old and new kllipper directories are automatically searched.

If the filament is not reaching the extruder then you either don't have a long enough default `default_calibration_length' in ercf_parameters.  This is used just for the initial calibration of extruder location,    Or you don't have a long enough `extruder_homing_max` (the distance to look over). Or possibly lots of slippage.  The default configuration is just that - something to get you started with..
