### ISSUE TITLE
ERCF_CALIBRATE retract extruder motor

### ISSUE THREAD

**Issue by mochoandre** [moggieuk/ERCF-Software-V3#41]
When I do ERCF_CALIBRATE filament gets caught in extruder and ERCF_CALIBRATE can not complete it's retractions (even thought it does not show any error and it says it passes to next tool has notjhing happenned, but really keeps at same same tool), maybe it was a good idea to do some retract at extruder side before or at the same time that ERCF_CALIBRATE retracts....

Just an Idea. 

Nice  Job you have done
Best regards

**Comment by moggieuk** [comment]
Hi. The problem is that the filament should not go into the extruder.  If it does so it is demonstrating that homing is not working (or perhaps your initial default value to put in ercf_parameters is longer than the real value -- needs to be 50mm shorter to give room to find hom).  If you have a CW2 extruder then I suspect the screw that limits closure of the BMG gear is leaving the gears too open and perhaps your homing current should be reduced even more.  This is a difficult condition to detect and extruder movement is only possible when it is hot (which is not really what people want when calibrating).   It will be detected and extracted if you have sensorless selector homing because this can detect a blocked gate and recover..

I'm going to close as not planned because I don't think it is workable.
