### ISSUE TITLE
Sync extrusion problem: the gear motor current setting seemed do not work reliably

### ISSUE THREAD

**Issue by SHKinsem** [moggieuk/ERCF-Software-V3#79]
![CC8 33SXHBY9H )515S{P{0](https://github.com/moggieuk/ERCF-Software-V3/assets/84130523/c6caf08b-72b5-4fbb-8b4f-c07113c13a8d)

As shown in the screenshot, while I was printing some test parts (since I am new to ercf) with the sync extrusion enabled.

I noticed that every time:
1, an issue occurs
2, issue fixed and 'ERCF_UNLOCK' as well as 'RESUME' is sent
3, at the time the status is printed in the console

the current would be reduced again. It looks like the macro is setting the current base on previous current setting rather than the value defined in the .cfg file, is this a bug? may I ask why the macro works like that?

**Comment by moggieuk** [comment]
I believe this bug has been fixed.  I was due to the fact that Klipper (TMC) only allows discrete steps in current.  The restored current was what was read rather than an internal starting value..

Use update-manger to update Happy Hare and all should be good.

I'm going to close this issue because I confident in the fix, but please re-open if something similar occurs...
